---
distribution_specific:
    Debian:
        sshd_service_name: ssh
    CentOS:
        sshd_service_name: sshd

git_mirror_repos:
  ctrlp.vim:
    url: https://github.com/kien/ctrlp.vim.git
  jedi-vim:
    url: https://github.com/davidhalter/jedi-vim.git
  nerdtree:
    url: https://github.com/scrooloose/nerdtree
  vim-airline:
    url: https://github.com/bling/vim-airline.git
  vim-autoformat:
    url: https://github.com/Chiel92/vim-autoformat.git
  vim-flake8:
    url: https://github.com/nvie/vim-flake8.git
  oh-my-zsh:
    url: https://github.com/robbyrussell/oh-my-zsh.git

yum_repos:
  CentOS-7-x86_64: http://ftp.prz.edu.pl/centos/7/os/x86_64/
  CentOS-6-x86_64: http://ftp.prz.edu.pl/centos/6.6/os/x86_64/

apt_repos:
  Debian-7-x86_64: http://ftp.agh.edu.pl/debian
  Debian-8-x86_64: http://ftp.agh.edu.pl/debian
  Ubuntu-14-x86_64: ftp://ftp.agh.edu.pl/ubuntu

netinst_uris:
  Debian-7-x86_64: /dists/wheezy/main/installer-amd64/current/images/netboot/debian-installer/amd64/
  Debian-8-x86_64: /dists/jessie/main/installer-amd64/current/images/netboot/debian-installer/amd64/
  Ubuntu-14-x86_64: /dists/trusty/main/installer-amd64/current/images/netboot/ubuntu-installer/amd64/

proxing_enabled: True
