---
distribution_specific:
    Debian:
        sshd_service_name: ssh
    CentOS:
        sshd_service_name: sshd

git_mirror_repos:
  - { url: "https://github.com/kien/ctrlp.vim.git", location: "ctrlp.vim"}
  - { url: "https://github.com/davidhalter/jedi-vim.git", location: "jedi-vim"}
  - { url: "https://github.com/scrooloose/nerdtree", location: "nerdtree"}
  - { url: "https://github.com/bling/vim-airline.git", location: "vim-airline"}
  - { url: "https://github.com/Chiel92/vim-autoformat.git", location: "vim-autoformat"}
  - { url: "https://github.com/nvie/vim-flake8.git", location: "vim-flake8"}
  - { url: "https://github.com/robbyrussell/oh-my-zsh.git", location: "oh-my-zsh"}

yum_repos:
  CentOS-7-x86_64: http://ftp.prz.edu.pl/centos/7/os/x86_64/
  CentOS-6-x86_64: http://ftp.prz.edu.pl/centos/6.6/os/x86_64/

apt_repos:
  Debian-7-x86_64: http://ftp.agh.edu.pl/debian
