---
apache2_base_extra_modules:
  RedHat:
    - 10-wsgi.conf
    - 00-ssl.conf
apache2_base_extra_packages:
  RedHat:
    - mod_wsgi

apache2_base_http_sockets:
  - host: "{{ ansible_default_ipv4.address }}"
    port: 80
  - host: 127.0.0.1
    port: 80

apache2_base_https_sockets:
  - host: "{{ ansible_default_ipv4.address }}"
    port: 443

apache2_base_prefork_start_servers: 5
apache2_base_prefork_min_spare_servers: 2
apache2_base_prefork_max_spare_servers: 5
apache2_base_prefork_max_clients: 50
apache2_base_prefork_max_requests_per_child: 1000

apache2_base_php_enabled: False
apache2_base_monitoring: False

yum_repos:
  CentOS-7-x86_64: http://ftp.prz.edu.pl/centos/7/os/x86_64/
  CentOS-6.6-x86_64: http://ftp.prz.edu.pl/centos/6.6/os/x86_64/
