---
- fail: msg="This role currently supports only Fedora"
  when: ansible_distribution != 'Fedora'

- name: Install ClamAv packages
  action:
    module: "{{ ansible_pkg_mgr }}"
    state: present
    name: "{{ item }}"
  with_items: clamav_packages[ansible_os_family]

- name: Upload freshclam's configuration
  template:
    src: freshclam.conf.j2
    dest: /etc/freshclam.conf
    owner: root
    group: root
    mode: 0644

- name: Enable freshclam updates (RedHat)
  copy:
    src: freshclam.sysconfig.RedHat
    dest: /etc/sysconfig/freshclam
    owner: root
    group: root
    mode: 0644
  when: ansible_os_family == 'RedHat'
