---
- name: Include secrets for base hypervisor role
  include_vars: secrets/group_vars/all.yml
  tags:
    - base
    - secret

- name: Check if there are any hosts secrets
  stat: path="secrets/host_vars/{{ ansible_hostname  }}.yml"
  register: host_secrets_exist

- name: Include host secrets
  include_vars: "secrets/host_vars/{{ ansible_hostname }}.yml"
  tags:
    - secret
    - users
  when: host_secrets_exist.stat.exists == True

- include: packages.yml
  tags:
    - base
    - secret

- include: dirtree_setup.yml
  tags:
    - base
    - secret
