---
- name: Install Python dependencies on RHEL/CentOS
  action:
    module: "{{ ansible_pkg_mgr  }}"
    name: "{{ item }}"
    state: present
  with_items:
    - sqlite-devel
    - libsq3-devel
    - readline-devel
    - bzip2-devel
  when: ansible_os_family == 'RedHat'

- name: Install Python dependencies on Debian-like systems
  fail: "Needs some work"
  when: >
    ansible_os_family == 'Debian'

- name: Checkout pyenv
  git:
    repo: https://github.com/yyuu/pyenv.git
    dest: "/{{ item if item == 'root' else 'home/' + item  }}/.pyenv/"
    accept_hostkey: yes
    version: "{{ development_penv_version }}"
  with_items: "{{ users.keys() }}"
  when: >
    (item in local_users or item == 'root') and
    users[item]['is_python_user'] == True

- name: Checkout pyenv-virtualenv
  git:
    repo: https://github.com/yyuu/pyenv-virtualenv.git
    dest: "/{{ item if item == 'root' else 'home/' + item  }}/.pyenv/plugins/pyenv-virtualenv"
    accept_hostkey: yes
    version: "{{ development_penv_virtualenv_version }}"
  with_items: "{{ users.keys() }}"
  when: >
    (item in local_users or item == 'root') and
    users[item]['is_python_user'] == True

- name: Fix pyenv repo ownership
  file:
    name: "/{{ item if item == 'root' else 'home/' + item  }}/.pyenv/"
    owner: "{{ item }}"
    group: "{{ item }}"
  with_items: "{{ users.keys() }}"
  when: >
    (item in local_users or item == 'root') and
    users[item]['is_python_user'] == True

- name: Remove pyenv repo
  file:
    state: absent
    name: "/{{ item if item == 'root' else 'home/' + item  }}/.pyenv/"
  with_items: "{{ users.keys() }}"
  when: >
    (item in local_users or item == 'root') and
    users[item]['is_python_user'] == False

- name: Set penv profile variables and enable pyenv autoload
  template:
    src: pyenv-profile.sh.j2
    dest: "/{{ 'root' if item == 'root' else 'home/' + item  }}/.profile.d/pyenv.sh"
    owner: "{{ item }}"
    group: "{{ item }}"
    mode: 0640
  with_items: "{{ users.keys() }}"
  notify: assemble user profile files

- name: Remove pyenv profile files
  file:
    name: "/{{ 'root' if item == 'root' else 'home/' + item  }}/.profile.d/pyenv.sh"
    state: absent
  with_items: "{{ users.keys() }}"
  when: >
    (item in local_users or item == 'root') and
    users[item]['is_python_user'] == False
