---
- hosts: all:!hypervisors
  roles:
    - { role: proxy_settings, when: "minimal_base is not defined or minimal_base == False" }
    - base
    - { role: fw, when: "minimal_base is not defined or minimal_base == False" }

- hosts: pxeservers
  roles:
    - apache2_base
    - proxy
    - repo
    - cobbler
    - git_mirror

- hosts: hypervisors
  sudo: True
  connection: local
  roles:
    - dns
    - koan_patching

- hosts: openstack
  roles:
    - base

- hosts: d8t.tr
  roles:
    - alexeymedvedchikov.rabbitmq
