---
- hosts: all
  sudo: True
  roles:
    - users_all
    - base_all
    - sshd_config
    - sysdig
    - vim

- hosts: hypervisors
  sudo: True
  roles:
    - base_hypervisors
    - users_hypervisors
    - disk_schedulers
    - ssh-agent
    - vagrant
    - clamav
    - google-stuff
    - flash
    - skype
    - koan_patching
    - dns
    - syncthing
    - development

- hosts: vms
  roles:
    - users_vms
    - base_vms
    - disk_schedulers

- hosts: trusted:isolated
  roles:
    - proxy_settings

- hosts: jumphosts
  sudo: True
  roles:
    - fw_base
    - fw_jumphost

- hosts: mplay:c7t.tr
  sudo: True
  roles:
    - vagrant

- hosts: pxeservers
  roles:
    - apache2_base
    - proxy
    - repo
    - cobbler
