---
- fail: msg="This role requires systemd based distro"
  when: >
    ansible_os_family == 'RedHat' and
    (ansible_distribution != 'Fedora' or
    ansible_distribution == 'CentOS' and
    ansible_distribution_major_version != '7') or
    ansible_os_family == 'Debian' and
    ansible_distribution_major_version != '8'

- include: dirtree_setup.yml
  tags: syncthing

- include: sysctl.yml
  tags: syncthing

- include: syncthing.yml
  tags: syncthing

- include: syncthing-inotify.yml
  tags: syncthing

- meta: flush_handlers
