---
- name: Create repository dirs
  file:
    state: directory
    name: "/home/git/{{ item }}.git/"
    owner: git
    group: git
    mode: 0750
  with_items: git_mirror_repos.keys()

- name: Clone repositories
  git:
    bare: yes
    dest: "/home/git/{{ item }}.git/"
    force: yes
    repo: "{{ git_mirror_repos[item]['url'] }}"
  with_items: git_mirror_repos.keys()

- name: Fix permissions of repositories
  file:
    name: /home/git/
    owner: git
    group: git
    recurse: true
