---
- name: Install auxilary packages (Debian)
  action:
    module: "{{ ansible_pkg_mgr }}"
    name: "{{ item }}"
    state: present
  with_items:
    - libvirt-dev
    - ruby-dev
    - build-essential
    - ruby-builder

- name: Install virtualbox repository key (Debian)
  apt_key:
    data: "{{ lookup('file', '../files/oracle_vbox.asc') }}"
    state: present

- name: Install virtualbox repository (Debian)
  apt_repository:
    repo: "deb http://download.virtualbox.org/virtualbox/debian {{ ansible_distribution_release }} contrib"
    state: present
  notify: Debian update repos

# Update repository data _NOW_
- meta: flush_handlers

- name: Remove old virtualbox packages
  action:
    module: "{{ ansible_pkg_mgr }}"
    name: "{{ item }}"
    state: absent
  with_items:
    - virtualbox-4.3

- name: Install virtualbox packages
  action:
    module: "{{ ansible_pkg_mgr }}"
    name: "{{ item }}"
    state: present
  with_items:
    - dkms
    - virtualbox-5.0
