---
- name: Install tmux package
  action:
    module: "{{ ansible_pkg_mgr }}"
    name: tmux
    state: present

- name: Upload tmux config file
  template:
    src: tmux.conf.j2
    dest: "/{{ item if item == 'root' else 'home/' + item }}/.tmux.conf"
    owner: "{{ item }}"
    group: "{{ item }}"
    mode: 0640
  with_items: "{{users.keys()}}"
  when: >
    (item in local_users or item == 'root') and
    users[item]['is_tmux_user'] == True
