---
- name: Install Python packages for Fedora
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - python
    - python-ipdb
    - python-ipython
    - python-pip
    - python-virtualenv
    - python3
    - python3-ipdb
    - python3-ipython
    - python3-pip
    - python3-virtualenv
