---
- name: Install vagrant packages (Fedora)
  action:
    module: "{{ ansible_pkg_mgr }}"
    name: "{{ item }}"
    state: present
  with_items:
    - vagrant
  when: ansible_os_family == 'RedHat' and ansible_distribution == 'Fedora'

- name: Install vagrant packages (CentOS)
  action:
    module: "{{ ansible_pkg_mgr }}"
    name: https://dl.bintray.com/mitchellh/vagrant/vagrant_1.7.4_x86_64.rpm
    state: present
  when: ansible_os_family == 'RedHat' and ansible_distribution == 'CentOS'

- name: Install vagrant packages (Debian)
  action:
    module: "{{ ansible_pkg_mgr }}"
    name: https://dl.bintray.com/mitchellh/vagrant/vagrant_1.7.4_x86_64.deb
    state: present
  when: ansible_os_family == 'Debian'

- name: Install auxilary packages (RedHat)
  action:
    module: "{{ ansible_pkg_mgr }}"
    name: "{{ item }}"
    state: present
  with_items:
    - libvirt-devel
    - ruby-devel
    - gcc
    - gcc-c++
  when: ansible_os_family == 'RedHat'

- name: Install auxilary packages (Debian)
  action:
    module: "{{ ansible_pkg_mgr }}"
    name: "{{ item }}"
    state: present
  with_items:
    - libvirt-dev
    - ruby-dev
    - gcc
    - gcc-c++
    - rubygem-builder
  when: ansible_os_family == 'Debian'

- name: Find installed plugins
  shell: "vagrant plugin list | cut -d' ' -f 1"
  register: vagrant_installed_plugins
  always_run: true
  changed_when: False
  become: yes
  become_user: "{{ item }}"
  with_items: "{{ users.keys() | sort() }}"
  when: >
    (item in local_users or item == 'root') and
    users[item]['is_vagrant_user'] == True

- debug: var=vagrant_installed_plugins

- name: Install missing vagrant plugins
  command: "vagrant plugin install {{ item[2] }}"
  with_nested:
    - vagrant_installed_plugins.results
    - users.keys()
    - vagrant_required_plugins
  become: yes
  become_user: "{{ item[1] }}"
  when: >
    (item[1] in local_users or item[1] == 'root') and
    users[item[1]]['is_vagrant_user'] == True and
    ('skipped' not in item[0] or item[0]['skipped'] == False) and
    item[0]["item"] == item[1] and
    item[2] not in item[0]["stdout_lines"]

- name: Calculate differences between current plugins list and desired plugins
  action: nested_looping_helper
  args:
    current_elements_hash: '{{ vagrant_installed_plugins }}'
    desired_elements_list: '{{ vagrant_required_plugins }}'
    output_variable_name: vagrant_redundant_plugins

- debug: var=vagrant_redundant_plugins

- name: Remove redundant vagrant plugins
  command: "vagrant plugin uninstall {{ item.item_val }}"
  become: yes
  become_user: "{{ item.item_key }}"
  with_items: vagrant_redundant_plugins
  when: item.item_val != 'vagrant-share'

- name: Install virtualbox repository key (Debian)
  apt_key:
    file: oracle_vbox.asc
    state: present
  when: ansible_os_family == 'Debian'

#http://serverfault.com/questions/733319/ansible-enable-repo-and-add-pgp-key-on-centos-7
- name: Install virtualbox repository key (RedHat)
  copy:
    src: oracle_vbox.asc
    dest: /etc/pki/rpm-gpg/RPM-GPG-KEY-oracle-vbox
    owner: root
    group: root
    mode: 0644
  when: ansible_os_family == 'RedHat'

- name: Install virtualbox repository (Debian)
  apt_repository:
    content: "deb http://download.virtualbox.org/virtualbox/debian {{ ansible_distribution_release }} contrib"
    state: present
  when: ansible_os_family == 'Debian'

- name: Install virtualbox repository (RedHat)
  copy:
    src: "virtualbox.{{ ansible_distribution }}.repo"
    dest: /etc/yum.repos.d/virtualbox.repo
  when: ansible_os_family == 'RedHat'

- name: Install virtualbox packages
  action:
    module: "{{ ansible_pkg_mgr }}"
    name: "{{ item }}"
    state: present
  with_items:
    - dkms
    - VirtualBox-4.3
