---
- name: Upload Docker repo config
  copy:
    src: docker.repo-Fedora
    dest: /etc/yum.repos.d/docker.repo
    owner: root
    group: root
    mode: 0644

- name: Make sure native Fedora docker package is not installed
  action:
    module: "{{ ansible_pkg_mgr }}"
    name: docker
    state: absent

- name: Install Docker
  action:
    module: "{{ ansible_pkg_mgr }}"
    name: docker-engine
    state: present
