---
# $ lvcreate --wipesignatures y -n thinpool docker -l 95%VG
# $ lvcreate --wipesignatures y -n thinpoolmeta docker -l 1%VG
# lvconvert -y --zero n -c 512K --thinpool vg-main/docker-thinpool
# --poolmetadata vg-main/docker-thinpool-meta

- name: Upload docker-clean cleanup script
  copy:
    src: docker-clean.sh
    dest: /opt/docker-clean.sh
    owner: root
    group: root
    mode: 0744

- name: Setup a cron job for docker containers cleanup
  copy:
    src: docker-cleanup.sh-cronjob
    dest: /etc/cron.hourly/docker-cleanup.sh
    owner: root
    group: root
    mode: 0744

- name: Upload genconf purging script
  copy:
    src: docker-purge-old.sh
    dest: /opt/docker-purge-old.sh
    owner: root
    group: root
    mode: 0755

- name: Upload docker configuration
  copy:
    src: daemon.json
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: 0644
  notify: Restart Docker

- name: Tune Docker socket configuration
  copy:
    src: docker.socket
    dest: /usr/lib/systemd/system/docker.socket
    owner: root
    group: root
    mode: 0644
  notify:
    - reload systemd
    - Restart Docker

- name: Enable Docker service
  service:
    name: docker
    enabled: true
    state: started

- name: Disable storage setup service
  copy:
    content: STORAGE_DRIVER=""
    dest: /etc/sysconfig/docker-storage-setup
    owner: root
    group: root
    mode: 0644

- name: Set docker env variables per-profile
  template:
    src: docker-profile.sh.j2
    dest: "/{{ 'root' if item == 'root' else 'home/' + item  }}/.profile.d/docker.sh"
    owner: "{{ item }}"
    group: "{{ item }}"
    mode: 0640
  with_items: "{{users.keys()}}"
  notify: assemble user profile files
  when: >
    item == 'root' or item in local_users
