---
- name: reload systemd
  command: systemctl daemon-reload

- name: sysctl reload
  command: sysctl -p --system

- name: udev reload
  command: udevadm control --reload-rules

- name: restart sshd
  service:
    name: '{{ distribution_specific[ansible_distribution]["sshd_service_name"] }}'
    state: restarted

- name: restart cobbler
  service:
    name: cobblerd
    state: restarted

- name: restart httpd
  service:
    name: cobblerd
    state: restarted

- name: restart journalctl
  service:
    name: systemd-journald
    state: restarted

- name: reload named
  service:
    name: named
    state: reloaded

- name: restart named
  service:
    name: named
    state: restarted

- name: restart syncthing
  service:
    name: "syncthing@{{ item }}.service"
    state: restarted
  with_items: users.keys()
  when: >
    item in local_users and
    users[item]['is_syncthing_user'] == True

- name: restart syncthing-inotify
  service:
    name: "syncthing-inotify@{{ item }}.service"
    state: restarted
  with_items: users.keys()
  when: >
    item in local_users and
    users[item]['is_syncthing_user'] == True
