---
- name: Fail if not run on RHEL/CentOS 7
  fail:
    msg: "This role is suitable/was tested on RHEL/CentOS 7"
  when: "ansible_os_family != 'RedHat' or \
        ansible_os_family == 'RedHat'and ansible_distribution_major_version <= 7"

- name: Install cobbler
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - cobbler
    - cobbler-web
  notify: Restart Apache

- name: Enable cobbler services
  service:
    name: "{{ item }}"
    state: running
    enabled: yes
  with_items:
    - cobblerd
    - httpd
