---
- name: Fail if not run on RHEL/CentOS 7
  fail:
    msg: "This role is suitable/was tested on RHEL/CentOS 7"
  when: "ansible_os_family != 'RedHat' or \
        ansible_os_family == 'RedHat'and ansible_distribution_major_version <= 7"

- name: Install cobbler
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - cobbler
    - cobbler-web
    - dhcp
    - syslinux
    - bind
  notify: Restart apache

- name: Include apache2 vars file
  include_vars: ../../apache2_base/vars/main.yml

- name: Create SSL dir for HTTPd
  file:
    name: /etc/httpd/ssl/
    state: directory
    owner: root
    group: "{{ apache2_base_runas_user[ansible_os_family] }}"
    mode: 0710

- name: Upload cobbler certificate
  copy:
    src: "data/ssl/cobbler.{{ hypervisor }}.vespian.net.crt"
    dest: "/etc/httpd/ssl/cobbler.{{ hypervisor }}.vespian.net.crt"
    owner: root
    group: "{{ apache2_base_runas_user[ansible_os_family] }}"
    mode: 0640
  notify: Restart apache

- name: Include cobbler certificate key
  include_vars: "secrets/ssl/cobbler.{{ hypervisor }}.vespian.net.key"
  tags: secret

- name: Upload cobbler certificate key
  copy:
    content: "{{ cobbler_cert_key | b64decode}}"
    dest: "/etc/httpd/ssl/cobbler.{{ hypervisor }}.vespian.net.key"
    owner: root
    group: "{{ apache2_base_runas_user[ansible_os_family] }}"
    mode: 0640
  notify: Restart apache
  tags: secret

- name: Configure cobbler vhosts
  template:
    src: "{{ item }}.conf.j2"
    dest: "/etc/httpd/conf.d/{{ item }}.conf"
    owner: root
    group: "{{ apache2_base_runas_user[ansible_os_family] }}"
    mode: 0640
  notify: Reload apache
  with_items:
    - cobbler
    - cobbler_web

- name: Configure mod_wsgi
  copy:
    src: mod_wsgi.conf
    dest: /etc/httpd/conf.modules.d/10-wsgi.conf
    owner: root
    group: "{{ apache2_base_runas_user[ansible_os_family] }}"
    mode: 0640
  notify: Restart apache

- name: Upload authorization information for Cobbler
  copy:
    src: users.digest
    dest: /etc/cobbler/users.digest
    owner: root
    group: root
    mode: 0644

- name: Setup SELinux for cobbler
  seboolean:
    name: "{{ item }}"
    state: yes
    persistent: true
  with_items:
    - httpd_serve_cobbler_files
    - httpd_can_network_connect_cobbler
    - cobbler_can_network_connect

- name: Enable cobbler services
  service:
    name: "{{ item }}"
    state: running
    enabled: yes
  with_items:
    - cobblerd
    - httpd
    - xinetd

# Hack, Hack, Hack!
# During initial provisioning, there are no systems defined, and DHCPd configuration
# will not be created by cobbler sync <sic!>. We need to only enable dhcpd for now
# , cobbler sync will start it later on.
- name: Start dhcpd service
  service:
    name: dhcpd
    enabled: yes
