---
- name: Fail if not run on Centos 7
  fail:
    msg: "This role is suitable/was tested on Centos 7"
  when: "ansible_os_family != 'RedHat' or \
        ansible_os_family == 'RedHat'and ansible_distribution_major_version <= 7"

- name: Install cobbler
  yum:
    name: cobbler
    state: present

- name: Enable cobbler services
  service:
    name: "{{ item }}"
    state: running
    enabled: yes
  with_items:
    - cobblerd
    - httpd
