---
- name: Create pxe images directories for CentOS
  file:
    name: "/var/lib/cobbler/pxe/{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0644
    setype: cobbler_var_lib_t
  with_items: yum_repos.keys()

- name: Download initrd and vmlinuz files for CentOS
  get_url:
    url: "{{ yum_repos[item[0]] }}/isolinux/{{ item[1]}}"
    dest: "/var/lib/cobbler/pxe/{{ item[0] }}/{{ item[1] }}"
    owner: root
    group: root
    mode: 0644
    setype: cobbler_var_lib_t
  with_nested:
    - yum_repos.keys()
    - [ "vmlinuz", "initrd.img" ]
