---
- name: Remove cobbler's default cruft
  file:
    name: "/etc/cobbler/{{ item }}"
    state: absent
  with_items:
    - cobbler_bash
    - completions
    - mongodb.conf

- name: Find default fencing scripts
  command: ls -1
  args:
    chdir: /etc/cobbler/power/
  register: power_scripts
  always_run: true
  changed_when: false

- name: Remove default fencing scripts
  file:
    name: "/etc/cobbler/power/{{ item }}"
    state: absent
  with_flattened:
    - power_scripts.stdout_lines
  when: "item != 'fence_virsh.template'"

- name: Upload configuration
  template:
    src: settings.j2
    dest: /etc/cobbler/settings
    owner: root
    group: "{{ apache2_base_runas_user[ansible_os_family] }}"
    mode: 0640
  notify: restart cobblerd

- name: Upload DHCP template
  template:
    src: dhcp.template.j2
    dest: /etc/cobbler/dhcp.template
    owner: root
    group: root
    mode: 0640
  notify: sync cobbler

- name: Upload modules configuration
  copy:
    src: modules.conf
    dest: /etc/cobbler/modules.conf
    owner: root
    group: root
    mode: 0640
  notify: restart cobblerd

- name: Copy base kickstart for RHEL systems
  template:
    src: "{{ item }}.j2"
    dest: "/var/lib/cobbler/kickstarts/{{ item }}"
    owner: root
    group: root
    mode: 0644
  notify: sync cobbler
  with_items:
    - red-hat.ks
    - debian.preseed.cfg

- name: Fix cobbler template snippets
  copy:
    src: kickstart_done
    dest: /var/lib/cobbler/snippets/kickstart_done
    owner: root
    group: root
    mode: 0644
  notify: sync cobbler

- name: Put debian post_run_deb script
  template:
    src: post_run_deb.j2
    dest: /var/lib/cobbler/snippets/post_run_deb
    owner: root
    group: root
    mode: 0644
  notify: sync cobbler

- name: Copy helper scripts to PXE server
  copy:
    src: "{{ item }}"
    dest: "/root/{{ item }}"
    owner: root
    group: root
    mode: 0755
  with_items:
    - cobbler_bootstrap.sh
    - create_CentOS6_vm.sh
    - create_CentOS7_vm.sh
    - create_Debian7_vm.sh
