---
- name: Remove cobbler's default cruft
  file:
    name: "/etc/cobbler/{{ item }}"
    state: absent
  with_items:
    - cobbler_bash
    - completions
    - mongodb.conf

- name: Find default fencing scripts
  command: ls -1
  args:
    chdir: /etc/cobbler/power/
  register: power_scripts
  always_run: true
  changed_when: false

- name: Remove default fencing scripts
  file:
    name: "/etc/cobbler/power/{{ item }}"
    state: absent
  with_flattened:
    - power_scripts.stdout_lines
  when: "item != 'fence_virsh.template'"

- name: Upload configuration
  template:
    src: settings.j2
    dest: /etc/cobbler/settings
    owner: root
    group: "{{ apache2_base_runas_user[ansible_os_family] }}"
    mode: 0640
  notify: restart cobblerd

- name: Upload DHCP template
  template:
    src: dhcp.template.j2
    dest: /etc/cobbler/dhcp.template
    owner: root
    group: root
    mode: 0640
  notify: sync cobbler

- name: Upload modules configuration
  copy:
    src: modules.conf
    dest: /etc/cobbler/modules.conf
    owner: root
    group: root
    mode: 0640
  notify: restart cobblerd
