---
base_all_extra_added_packages:
  common: []
  RedHat:
    common: []
    Centos:
      common: []
      6: []
      7: []
    Fedora:
      common: []
      21: []
      22: []
      23: []
  Debian:
    common: []

base_all_extra_removed_packages:
  common: []
  RedHat:
    common: []
    Centos:
      common: []
      6: []
      7: []
    Fedora:
      common: []
      21: []
      22: []
      23: []
  Debian:
    common: []

ip_forwarding: false
