---
- name: reload systemd
  command: systemctl daemon-reload

- name: sysctl reload
  command: sysctl -p /etc/sysctl.conf

- name: udev reload
  command: udevadm control --reload-rules

- name: restart sshd
  service:
    name: '{{ distribution_specific[ansible_distribution]["sshd_service_name"] }}'
    state: restarted

- name: restart cobbler
  service:
    name: cobblerd
    state: restarted

- name: restart httpd
  service:
    name: cobblerd
    state: restarted

- name: restart journalctl
  service:
    name: systemd-journald
    state: restarted

- name: reload named
  service:
    name: named
    state: reloaded

- name: restart named
  service:
    name: named
    state: restarted
