---
- name: Update software (Debian)
  apt:
    update_cache: True
    upgrade: full
  when: ansible_os_family == 'Debian'

- name: Perform cleanup of package manager (Debian)
  command: "{{ item }}"
  with_items:
    - apt-get -y autoremove
    - apt-get -y clean
  when: ansible_os_family == 'Debian'

- name: Update software (RedHat)
  action:
    module: "{{ ansible_pkg_mgr }}"
    name: '*'
    state: latest
    update_cache: yes
  when: ansible_os_family == 'RedHat'

- name: Perform cleanup of package manager (RedHat)
  command: "{{ item }}"
  with_items:
    - "{{ ansible_pkg_mgr  }} clean all"
  when: ansible_os_family == 'RedHat'
