---
- name: Include secrets
  include_vars: secrets/group_vars/all
  tags:
    - base
    - secret

- include: repos/repos.yml
  tags:
    - base

- include: packages.yml
  tags:
    - base

- include: sysctl.yml
  tags:
    - base

- include: basics.yml
  tags:
    - base

- include: ssh.yml
  tags:
    - base
    - net

#- include: python.yml
#  tags:
#    - base
#
#- include: "sysdig_Debian.yml"
#  tags:
#    - base
#  when: ansible_os_family == 'Debian'
#
#- include: "sysdig_RedHat.yml"
#  tags:
#    - base
#  when: ansible_os_family == 'RedHat'
#
## User specific:
#- include: users.yml
#  tags:
#    - base
#    - users
#
#- include: git.yml
#  tags:
#    - base
#
#- include: tmux.yml
#  tags:
#    - base
#
#- include: zsh.yml
#  tags:
#    - base
#    - users
#
#- include: vim.yml
#  tags:
#    - base
#    - users
