---
- include: "repos_Debian.yml"
  when: ansible_os_family == 'Debian'
  tags: base_all

- include: "repos_CentOS.yml"
  when: ansible_os_family == 'RedHat' and ansible_distribution == 'CentOS'
  tags: base_all

- include: "repos_Fedora.yml"
  when: ansible_os_family == 'RedHat' and ansible_distribution == 'Fedora'
  tags: base_all

- include: packages.yml
  tags: base_all

- include: sysctl.yml
  tags: base_all

- include: misc.yml
  tags: base_all

- include: "python_Debian.yml"
  when: ansible_os_family == 'Debian'
  tags: base_all

- include: "python_CentOS.yml"
  when: ansible_os_family == 'RedHat' and ansible_distribution == 'CentOS'
  tags: base_all

- include: "python_Fedora.yml"
  when: ansible_os_family == 'RedHat' and ansible_distribution == 'Fedora'
  tags: base_all

- include: git.yml
  tags: base_all

- include: tmux.yml
  tags: base_all

- include: zsh.yml
  tags: base_all

- meta: flush_handlers
