---
- include: repos/repos.yml
  tags: base_all

- include: packages.yml
  tags: base_all

- include: sysctl.yml
  tags: base_all

- include: misc.yml
  tags: base_all

- include: python/python.yml
  tags: base_all

- include: git.yml
  tags: base_all

- include: tmux.yml
  tags: base_all

- include: zsh.yml
  tags: base_all
