---
- name: Include secrets
  include_vars: secrets/group_vars/all
  tags:
    - base
    - secret

- include: repos/repos.yml
  tags:
    - base

- include: packages.yml
  tags:
    - base
    #- dupa

- include: sysctl.yml
  tags:
    - base

- include: misc.yml
  tags:
    - base

- include: python/python.yml
  tags:
    - base

- include: git.yml
  tags:
    - base
    - users

- include: tmux.yml
  tags:
    - base
    - users

- include: zsh.yml
  tags:
    - base
    - users
