---
- name: create folder for shared stuff
  file:
    state: directory
    owner: root
    group: root
    name: /home/shared/
    mode: 0755

- name: remove motd
  copy:
    content: ""
    dest: /etc/motd
    mode: 0644
    owner: root
    group: root

- name: Normalize sudo configuration and enable pipelining for ansible
  template:
    src: misc/sudoers.j2
    dest: /etc/sudoers
    mode: 0440
    owner: root
    group: root

- name: Configure journalctl
  copy:
    src: misc/journald.conf.RedHat
    dest: /etc/systemd/journald.conf
    mode: 0640
    owner: root
    group: root
  notify: restart journalctl
  when: >
    {{ ansible_os_family == 'RedHat' and
    (ansible_distribution == 'Fedora' or
    (ansible_distribution == 'CentOS' and
    ansible_distribution_major_version == '7')) or
    ansible_os_family == 'Debian' and
    ansible_distribution_major_version == '8' }}

- name: Make sure acpid demon is running
  service:
    name: acpid
    state: started
    enabled: true

- name: Create profile snippets directory
  file:
    state: directory
    name: "/{{ item if item == 'root' else 'home/' + item  }}/.profile.d/"
    owner: "{{ item }}"
    group: "{{ item }}"
    mode: 0750
  with_items: users.keys()
