---
- name: Install Python packages for Debian-like systems
  action:
    module: "{{ ansible_pkg_mgr  }}"
    name: "{{ item }}"
    state: present
  with_items:
    - python
    - python-ipdb
    - python-pip
    - python-virtualenv
    - python3
    - python3-ipdb
    - python3-pip
    - python3-virtualenv
    - ipython
    - ipython3
  when: >
    ansible_distribution_release == 'jessie' or
    item not in ['python3-virtualenv', 'python3-ipdb']

- name: Install remaining Python packages using pip
  pip:
    executable: "{{ item[1] }}"
    name: "{{ item[0] }}"
    state: present
  with_nested:
    - [ 'virtualenv', 'ipdb' ]
    - [ 'pip3', 'pip-3.2' ]
  when: >
    (ansible_distribution_release == 'wheezy'
    and item[1] != 'pip3') or
    (ansible_distribution == 'Ubuntu'
    and item[1] != 'pip-3.2' and item[0] != 'ipdb')
