---
- name: Install Python packages for Debian-like systems
  action:
    module: "{{ ansible_pkg_mgr  }}"
    name: "{{ item }}"
    state: present
  with_items:
    - python
    - python-ipdb
    - python-pip
    - python-virtualenv
    - python3
    - python3-ipdb
    - python3-pip
    - python3-virtualenv
    - ipython
    - ipython3
