---
- name: Remove default sysctl.conf
  copy:
    content: ""
    dest: /etc/sysct.conf
    mode: 0640
    owner: root
    group: root
  notify: sysctl reload

- name: Upload basic sysctl config
  template:
    src: "sysctl/{{ item }}.sysctl.conf.j2"
    dest: "/etc/sysctl.d/{{ item }}.sysctl.conf"
    mode: 0640
    owner: root
    group: root
  notify: sysctl reload
  with_items:
    - corepid
    - swappines
    - syncookies
    - sysrq
    - tcp_opts
    - ip_forwarding
