---
- name: Install zsh shell
  action:
    module: "{{ ansible_pkg_mgr }}"
    name: zsh
    state: present

- name: Clone oh-my-zsh repo from upstream
  git:
   repo: "{{ git_mirror_repos['oh-my-zsh']['url'] }}"
   dest: "/{{ item if item == 'root' else 'home/' + item }}/.oh-my-zsh/"
   accept_hostkey: yes
  with_items: users.keys()
  become: yes
  become_user: "{{ item  }}"
  when: users[item]['shell'] == '/bin/zsh'
  tags: secret

- name: Upload zshrc file
  template:
    src: zshrc.j2
    dest: "/{{ item if item == 'root' else 'home/' + item }}/.zshrc"
    mode: 0640
    owner: "{{ item }}"
    group: "{{ item }}"
  with_items: users.keys()
  when: users[item]['shell'] == '/bin/zsh'

#- name: Upload custom oh-my-zsh theme
  #copy:
    #src: vesclean.zsh-theme
    #dest: "/{{ item if item == 'root' else 'home/' + item }}/.oh-my-zsh/themes/vesclean.zsh-theme"
    #mode: 0640
    #owner: "{{ item }}"
    #group: "{{ item }}"
  #with_items: users.keys()
  #when: users[item]['shell'] == '/bin/zsh'

- name: Set users shell
  user:
    name: '{{ item.key }}'
    shell: '{{ item.value.shell }}'
  with_dict: users
