---
- name: Check if there are any hosts vars for the hypervisor
  local_action: stat "path=host_vars/{{ hypervisor }}.yml"
  register: hypervisor_vars_exist

- name: Include hypervisors vars
  include_vars: "host_vars/{{ hypervisor }}.yml"
  when: hypervisor_vars_exist.stat.exists == True
