---
- name: Include global secrets
  include_vars: secrets/group_vars/all.yml

- name: Check if there are any hosts secrets
  local_action: stat "path=secrets/host_vars/{{ inventory_hostname }}.yml"
  register: host_secrets_exist

- name: Include per-host secrets
  include_vars: "secrets/host_vars/{{ ansible_hostname }}.yml"
  when: host_secrets_exist.stat.exists == True

- name: Check if there are any hosts secrets for the hypervisor
  local_action: stat "path=secrets/host_vars/{{ hypervisor }}.yml"
  register: hypervisor_secrets_exist

- name: Include hypervisors secrets
  include_vars: "secrets/host_vars/{{ hypervisor }}.yml"
  when: hypervisor_secrets_exist.stat.exists == True
