---
- name: Include global secrets
  include_vars: secrets/group_vars/all.yml
  tags:
    - secret

- name: Check if there are any hosts secrets
  stat: path="secrets/host_vars/{{ ansible_hostname }}.yml"
  register: host_secrets_exist

- name: Include per-host secrets
  include_vars: "secrets/host_vars/{{ ansible_hostname }}.yml"
  tags:
    - secret
  when: host_secrets_exist.stat.exists == True
