---
- fail: msg="This role requires systemd based distro"
  when: >
    ansible_distribution not in ['Ubuntu', 'Debian', 'RedHat', 'CentOS', 'Fedora'] or
    ansible_os_family == 'RedHat' and
    (ansible_distribution == 'CentOS' and ansible_distribution_major_version|int < 7) or
    ansible_os_family == 'Debian' and
    (ansible_distribution == 'Ubuntu' and ansible_distribution_major_version|int < 15) or
    (ansible_distribution == 'Debian' and ansible_distribution_major_version|int < 8)

- include: ssh-agent.yml
  tags: ssh-agent

- meta: flush_handlers
