---
- name: Install golang packages for Fedora system
  action:
    module: "{{ ansible_pkg_mgr }}"
    name: "{{ item }}"
    state: present
  with_items:
    - golang
    - golang-bin
    - golang-docs
    - golang-godoc
    - golang-googlecode-tools-goimports
    - golang-src
