---
- name: Set golang env variables per-profile
  template:
    src: golang-profile.sh.j2
    dest: "/{{ 'root' if item == 'root' else 'home/' + item  }}/.profile.d/golang.sh"
    owner: "{{ item }}"
    group: "{{ item }}"
    mode: 0640
  with_items: "{{users.keys()}}"
  notify: assemble user profile files
  when: >
    item == 'root' or (item in local_users and users[item]["is_golang_user"] == True)

- name: Remove golang env vars for users that do not use Go
  file:
    name: "/{{ 'root' if item == 'root' else 'home/' + item  }}/.profile.d/golang.sh"
    state: absent
  with_items: "{{users.keys()}}"
  notify: assemble user profile files
  when: >
    item != 'root' and users[item]["is_golang_user"] == False

- name: Find out if golang is installed at all
  stat:
    path: /opt/go
  register: golang_installed

- name: Find version of currently installed Go compiler
  shell: /opt/go/bin/go version | awk '{print $3}'
  register: current_golang_version
  changed_when: False
  always_run: True
  when: golang_installed.stat.exists == True

- name: Download golang compiler
  get_url:
    url: "https://storage.googleapis.com/golang/{{ development_golang_pinned_version }}.linux-amd64.tar.gz"
    dest: "{{ '/tmp/' + development_golang_pinned_version + '.linux-amd64.tar.gz' }}"
    force: yes
    owner: root
    group: root
    mode: 0400
  when: >
    golang_installed.stat.exists == False or
    development_golang_pinned_version != current_golang_version.stdout

- name: Remove current golang environment
  file:
    path: /opt/go
    state: absent
  when: >
    golang_installed.stat.exists == False or
    development_golang_pinned_version != current_golang_version.stdout

- name: Unpack new golang environment
  command: tar -xf "{{ '/tmp/' + development_golang_pinned_version + '.linux-amd64.tar.gz' }}"
  args:
    chdir: /opt/
    creates: /opt/go
  when: >
    golang_installed.stat.exists == False or
    development_golang_pinned_version != current_golang_version.stdout

- name: Remove downloaded golang archive
  file:
    path: "{{ '/tmp/' + development_golang_pinned_version + '.linux-amd64.tar.gz' }}"
    state: absent
