---
- include: python/Debian.yml
  when: ansible_os_family == 'Debian'
  tags: development

- include: python/RedHat.yml
  when: ansible_os_family == 'RedHat'
  tags: development

- include: golang.yml
  tags: development

- meta: flush_handlers
