---
- name: Install development packages for Debian
  apt:
    name: "{{ item.name }}"
    state: present
    default_release: "{{ item.release | default('stable') }}"
  with_items:
    - {"name": "devscripts"}
    - {"name": "python-mock", "release": "jessie"}
    - {"name": "python3-mock", "release": "jessie"}
    - {"name": "python-yaml"}
    - {"name": "python3-yaml"}
    - {"name": "libyaml-dev"}
    - {"name": "python-all"}
    - {"name": "python3-all"}
    - {"name": "python-coverage"}
    - {"name": "python-dnspython"}
    - {"name": "python3-dnspython"}
    - {"name": "python-nose"}
    - {"name": "python3-nose"}
    - {"name": "dh-python", "release": "wheezy-backports"}
    - {"name": "python-pymisc"}
    - {"name": "python3-pymisc"}

- name: Install remaining development stuff using PIP (Debian)
  pip:
    executable: "{{ item[1] }}"
    name: "{{ item[0] }}"
    state: present
  with_nested:
    - [ 'coverage' ]
    - [ 'pip-3.2' ]
