---
- name: Upload puk-puk script
  template:
    src: pukpuk.sh.j2
    dest: /opt/pukpuk.sh
    owner: root
    group: root
    mode: 0755

- name: Remove PackageKit
  action:
    module: "{{ ansible_pkg_mgr  }}"
    name: PackageKit
    state: absent

- name: Clean up PackageKit files
  file:
    path: /var/cache/PackageKit
    state: absent
