---
base_common_packages:
    - acpid
    - binutils
    - bridge-utils
    - dstat
    - git
    - hping3
    - htop
    - iotop
    - iproute
    - iptables
    - less
    - links
    - lsof
    - man
    - ncdu
    - ncdu
    - net-tools
    - patch
    - pigz
    - psmisc
    - pv
    - python
    - python-pycurl
    - rsync
    - strace
    - sudo
    - sysstat
    - tcpdump
    - telnet
    - tmux
    - tree
    - wget
    - xfsprogs

base_rhel_common_packages:
    - bind-utils
    - libselinux-python
    - mtr
    - yum-utils
    - setools-console
    - pykickstart
    - policycoreutils-python
    - iputils

base_debian_common_packages:
    - aptitude
    - apt-file
    - bind9-host
    - bmon
    - dnsutils
    - mtr-tiny
    - netcat
    - pbzip2
    - python-apt
    - python-selinux

base_rhel6_packages:
    - nc
    - pbzip2

base_rhel7_packages:
    - nmap-ncat
    # - pbzip2 # not in EPEL yet

base_common_redundant_packages:
    - cups

base_rhel_redundant_packages:
    - iprutils
    - autofs
    - tuned
    - lm_sensors

base_debian_redundant_packages:
    - lm-sensors
