---
- name: create non-root groups
  group:
    name: "{{ item.key }}"
    gid: "{{ item.value.gid }}"
    state: present
  with_dict: users
  when: item.key != 'root'

- name: create non-root users
  user:
    name: "{{ item.key }}"
    uid: "{{ item.value.uid }}"
    group: "{{ item.key }}"
    groups: '{{ distribution_specific[ansible_distribution]["sudo_group_name"] if item.value.is_sudoer == true else "" }}'
    createhome: yes
    state: present
  with_dict: users
  when: item.key != 'root'

- name: set ssh-keys for users permitted to login
  authorized_key:
    user: '{{ item.user }}'
    manage_dir: yes
    state: present
    key: "{{ login_key[item.host] }}"
  with_items: authorized_login_keys
  when: users[item.user]['ssh_login_permitted'] == True

#- name: remove ssh-keys from users denied ssh login
  #authorized_key:
    #user: '{{ item[0] }}'
    #manage_dir: yes
    #state: absent
  #with_nested:
    #- users.keys()
    #- login_key.keys()
  #when: "item[0] != 'root' and users[item[0]]['ssh_login_permitted'] == False"
