---
- name: Update software (Debian)
  apt:
    update_cache: True
    upgrade: full
  when: ansible_os_family == 'Debian'

- name: Perform cleanup of package manager (Debian)
  command: "{{ item }}"
  with_items:
    - apt-get -y autoremove
    - apt-get -y clean
  when: ansible_os_family == 'Debian'
