---
- name: set passwords for all the users
  user:
    name: "{{ item.key }}"
    password: "{{ item.value.pass_crypted }}"
  with_dict: users

- name: remove private key of obsoleted git_mirror role
  file:
    name: /root/.ssh/git-mirror_rsa
    state: absent
