---
- name: Include secrets
  include_vars: secrets/group_vars/all
  tags:
    - secret
    - users

- name: Check if there are any hosts secrets
  stat: path="secrets/host_vars/{{ ansible_hostname  }}.yml"
  register: host_secrets_exist

- name: Include host secrets
  include_vars: "secrets/host_vars/{{ ansible_hostname }}.yml"
  tags:
    - secret
    - users
  when: host_secrets_exist.stat.exists == True

- include: users.yml
  tags:
    - users
    - secret
