---
- name: Provide a list of common packages for Debian and RHEL/CentOS
  set_fact:
    common_packages:
      - acpid
      - binutils
      - dstat
      - git
      - hping3
      - htop
      - iotop
      - iproute
      - iptables
      - less
      - links
      - lsof
      - man
      - ncdu
      - ncdu
      - net-tools
      - patch
      - pigz
      - psmisc
      - pv
      - python
      - python-pycurl
      - rsync
      - strace
      - sudo
      - sysstat
      - tcpdump
      - telnet
      - tmux
      - tree
      - wget
      - xfsprogs

- name: Install RHEL/CentOS 6 specific packages
  yum:
    name: "{{ item }}"
    state: present
  with_flattened:
    - nc
    - pbzip2
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version == '6'

- name: Install RHEL/CentOS 7 specific packages
  yum:
    name: "{{ item }}"
    state: present
  with_flattened:
    - nmap-ncat
    # - pbzip2 # not in EPEL yet
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'

- name: Install base packages for RHEL/CentOS (all versions)
  yum:
    name: "{{ item }}"
    state: present
  with_flattened:
    - common_packages
    - bind-utils
    - libselinux-python
    - mtr
    - yum-utils
    - setools-console
    - pykickstart
    - policycoreutils-python
    - iputils
  when: ansible_os_family == 'RedHat'

- name: Install base packages for Debian
  apt:
    name: "{{ item }}"
    state: present
  with_flattened:
    - common_packages
    - aptitude
    - apt-file
    - bind9-host
    - bmon
    - dnsutils
    - mtr-tiny
    - netcat
    - pbzip2
    - python-apt
    - python-selinux
  when: ansible_os_family == 'Debian'

- name: provide a common list of redundant packages
  set_fact:
    unwanted_packages:
      - cups

- name: remove redundant packages (Debian)
  apt:
    name: "{{ item }}"
    state: absent
  with_flattened:
    - lm-sensors
    - unwanted_packages
  when: ansible_os_family == 'Debian'

- name: remove redundant packages (RHEL/CentOS)
  yum:
    name: "{{ item }}"
    state: absent
  with_flattened:
    - iprutils
    - autofs
    - tuned
    - lm_sensors
    - unwanted_packages
  when: ansible_os_family == 'RedHat'

- name: Tune sysctls
  template:
    src: sysctl.conf.j2
    dest: /etc/sysctl.conf
    mode: 0644
    owner: root
    group: root
  notify: sysctl reload

- name: noop scheduler by default for all virtual drives
  copy:
    src: schedulers.rules
    dest: /etc/udev/rules.d/60-schedulers.rules
    mode: 0644
    owner: root
    group: root
  notify: udev reload

- name: remove motd
  copy:
    content: ""
    dest: /etc/motd
    mode: 0644
    owner: root
    group: root

- name: Normalize sudo configuration and enable pipelining for ansible
  template:
    src: sudoers.j2
    dest: /etc/sudoers
    mode: 0440
    owner: root
    group: root

- name: Configure journalctl (RHEL/CentOS)
  copy:
    src: journald.conf.centos
    dest: /etc/systemd/journald.conf
    mode: 0640
    owner: root
    group: root
  notify: restart journalctl
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'

- name: Make sure acpid demon is running
  service:
    name: acpid
    state: started
    enabled: true
