---
- name: Tune sysctls
  template:
    src: sysctl.conf.j2
    dest: /etc/sysctl.conf
    mode: 0644
    owner: root
    group: root
  notify: sysctl reload

- name: noop scheduler by default for all virtual drives
  copy:
    src: schedulers.rules
    dest: /etc/udev/rules.d/60-schedulers.rules
    mode: 0644
    owner: root
    group: root
  notify: udev reload

- name: remove motd
  copy:
    content: ""
    dest: /etc/motd
    mode: 0644
    owner: root
    group: root

- name: Normalize sudo configuration and enable pipelining for ansible
  template:
    src: sudoers.j2
    dest: /etc/sudoers
    mode: 0440
    owner: root
    group: root

- name: Configure journalctl (RHEL/CentOS)
  copy:
    src: journald.conf.centos
    dest: /etc/systemd/journald.conf
    mode: 0640
    owner: root
    group: root
  notify: restart journalctl
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'

- name: Make sure acpid demon is running
  service:
    name: acpid
    state: started
    enabled: true
