---
- name: Provide a list of common packages for Debian and Centos
  set_fact:
    common_packages:
      - binutils
      - htop
      - iproute
      - iptables
      - less
      - lsof
      - ncdu
      - pigz
      - psmisc
      - pv
      - python
      - python-pycurl
      - strace
      - sudo
      - sysstat
      - tcpdump
      - telnet
      - tree
      - zsh

- name: Install CentOS 6 specific packages
  yum:
    name: "{{ item }}"
    state: present
  with_flattened:
    - nc
    - pbzip2
  when: ansible_distribution == 'CentOS' and ansible_distribution_major_version == '6'

- name: Install CentOS 7 specific packages
  yum:
    name: "{{ item }}"
    state: present
  with_flattened:
    - nmap-ncat
    # - pbzip2 # not in EPEL yet
  when: ansible_distribution == 'CentOS' and ansible_distribution_major_version == '7'

- name: Install base packages for CentOS (all versions)
  yum:
    name: "{{ item }}"
    state: present
  with_flattened:
    - common_packages
    - bind-utils
    - libselinux-python
    - mtr
    - vim-enhanced
  when: ansible_distribution == 'CentOS'

- name: Install base packages for Debian
  apt:
    name: "{{ item }}"
    state: present
  with_flattened:
    - common_packages
    - aptitude
    - bind9-host
    - bmon
    - dnsutils
    - mtr-tiny
    - netcat
    - pbzip2
    - python-apt
    - python-selinux
    - vim-nox
  when: ansible_distribution == 'Debian'

- name: provide a common list of redundant packages
  set_fact:
    unwanted_packages:
      - cups

- name: remove redundant packages (Debian)
  apt:
    name: "{{ item }}"
    state: absent
  with_flattened:
    - lm-sensors
    - unwanted_packages
  when: ansible_distribution == 'Debian'

- name: remove redundant packages (Centos)
  yum:
    name: "{{ item }}"
    state: absent
  with_flattened:
    - iprutils
    - autofs
    - lm_sensors
    - unwanted_packages
  when: ansible_distribution == 'CentOS'

- name: Tune sysctls
  template:
    src: sysctl.conf.j2
    dest: /etc/sysctl.conf
    mode: 0644
    owner: root
    group: root
  notify: sysctl reload

- name: noop scheduler by default for all virtual drives
  copy:
    src: schedulers.rules
    dest: /etc/udev/rules.d/60-schedulers.rules
    mode: 0644
    owner: root
    group: root
  notify: udev reload

- name: remove motd
  copy:
    content: ""
    dest: /etc/motd
    mode: 0644
    owner: root
    group: root
