---
- name: Install git (Debian)
  apt:
    name: git
    state: present
  when: ansible_distribution == 'Debian'

- name: Install git (CentOS)
  yum:
    name: git
    state: present
  when: ansible_distribution == 'CentOS'

- name: Upload gitconfig and gitignore files
  copy:
    src: "{{ item }}"
    dest: "/root/.{{ item }}"
    mode: 0640
    owner: root
    group: root
  with_items:
    - gitignore
    - gitconfig
