---
- name: Install git (Debian)
  action:
    module: "{{ ansible_pkg_mgr }}"
    name: git
    state: present

- name: Upload gitconfig and gitignore files
  copy:
    src: "{{ item[0] }}"
    dest: "/{{ item[1] if item[1] == 'root' else 'home/' + item[1] }}/.{{ item[0] }}"
    mode: 0640
    owner: "{{ item[1] }}"
    group: "{{ item[1] }}"
  with_nested:
    - [ 'gitignore', 'gitconfig']
    - users.keys()
  when: item[1] == 'root' or users[item[1]]['ssh_login_permitted'] == True
