---
- name: Include secrets
  include_vars: secrets/group_vars/all
  tags:
    - base
    - users
    - net
    - secret

- name: Include git_mirror private ssh key
  include_vars: secrets/ssh/git-mirror_rsa.yml
  tags:
    - base
    - secret

- include: "network_{{ ansible_os_family }}.yml"
  tags:
    - base
    - net

- include: "repos_{{ ansible_os_family }}.yml"
  tags:
    - base

- include: packages.yml
  tags:
    - base

- include: basics.yml
  tags:
    - base

- include: ssh.yml
  tags:
    - base
    - net

- include: python.yml
  tags:
    - base

- include: "sysdig_{{ ansible_os_family }}.yml"
  tags:
    - base

# User specific:
- include: users.yml
  tags:
    - base
    - users

- include: git.yml
  tags:
    - base

- include: zsh.yml
  tags:
    - base
    - users

- include: vim.yml
  tags:
    - base
    - users
