---
- name: Include secrets
  include_vars: secrets/group_vars/all
  tags:
    - base
    - users
    - net
    - secret

- name: Include git_mirror private ssh key
  include_vars: secrets/ssh/git-mirror_rsa.yml
  tags:
    - base
    - secret
    - users

- include: "network_Debian.yml"
  tags:
    - base
    - net
  when: ansible_os_family == 'Debian' and minimal_base == False

- include: "network_RedHat.yml"
  tags:
    - base
    - net
  when: ansible_os_family == 'RedHat' and minimal_base == False

- include: "repos_Debian.yml"
  tags:
    - base
  when: ansible_os_family == 'Debian'

- include: "repos_RedHat.yml"
  tags:
    - base
  when: ansible_os_family == 'RedHat'

- include: packages.yml
  tags:
    - base

- include: basics.yml
  tags:
    - base

- include: ssh.yml
  tags:
    - base
    - net

- include: python.yml
  tags:
    - base

- include: "sysdig_Debian.yml"
  tags:
    - base
  when: ansible_os_family == 'Debian'

- include: "sysdig_RedHat.yml"
  tags:
    - base
  when: ansible_os_family == 'RedHat'

# User specific:
- include: users.yml
  tags:
    - base
    - users

- include: git.yml
  tags:
    - base

- include: tmux.yml
  tags:
    - base

- include: zsh.yml
  tags:
    - base
    - users

- include: vim.yml
  tags:
    - base
    - users
