---
- name: Stop the resolvconf service
  service:
    name: resolvconf
    state: stopped
    enabled: false
  when: ansible_distribution == "Ubuntu"

- name: Create networking configuration snippets dir (Debian)
  file:
    path: /etc/network/interfaces.d/
    state: directory
    mode: 0750
    owner: root
    group: root
  notify: "restart Debian networking"

- name: Upload main netconf inclusion snippet
  copy:
    dest: /etc/network/interfaces
    content: "source /etc/network/interfaces.d/*"
    mode: 0750
    owner: root
    group: root
  notify: "restart Debian networking"

- name: Upload lo network configuration snippet (Debian)
  copy:
    src: interfaces.lo.debian
    dest: /etc/network/interfaces.d/interfaces.lo.cfg
    mode: 0644
    owner: root
    group: root
  notify: "restart Debian networking"

- name: Upload eth0 network configuration snippet (Debian)
  template:
    src: interfaces.eth0.debian.j2
    dest: /etc/network/interfaces.d/interfaces.eth0.cfg
    mode: 0644
    owner: root
    group: root
  notify: "restart Debian networking"

- name: Upload resolv.conf configuration
  template:
    src: resolv.conf.j2
    dest: /etc/resolv.conf
    mode: 0644
    owner: root
    group: root

- name: Upload /etc/hosts configuration
  template:
    src: hosts.j2
    dest: /etc/hosts
    mode: 0644
    owner: root
    group: root
