---
# On Centos7, rpm removal does not stop the service and after removing the rpm
# we cannot stop the service. OTOH later there is no NetworkManger script and
# service module fails. So we first test if rpm package is present.
- name: Check if NetworkManager is installed
  command:
    rpm -q NetworkManager
  ignore_errors: True
  register: _rpm_nm_out
  when: ansible_distribution == 'CentOS'
  changed_when: False

- name: Stop the Network Manager
  service:
    name: NetworkManager
    state: stopped
    enabled: false
  when: ansible_distribution == 'CentOS' and _rpm_nm_out.rc == 0

- name: Remove Network Manager
  yum:
    name: NetworkManager
    state: absent
  when: ansible_distribution == 'CentOS' and _rpm_nm_out.rc == 0

- name: Make ip configuration static instead of DHCP (Centos)
  template:
    src: ifcfg-eth0.centos.j2
    dest: /etc/sysconfig/network-scripts/ifcfg-eth0
    mode: 0644
    owner: root
    group: root
  notify: "restart CentOS networking"
  when: ansible_distribution == 'CentOS'

- name: Create networking configuration snippets dir (Debian)
  file:
    path: /etc/network/interfaces.d/
    state: directory
    mode: 0750
    owner: root
    group: root
  notify: "restart Debian networking"
  when: ansible_distribution == 'Debian'

- name: Upload lo network configuration snippet (Debian)
  copy:
    src: interfaces.lo.debian
    dest: /etc/network/interfaces.d/interfaces.lo
    mode: 0644
    owner: root
    group: root
  notify: "restart Debian networking"
  when: ansible_distribution == 'Debian'

- name: Upload eth0 network configuration snippet (Debian)
  template:
    src: interfaces.eth0.debian.j2
    dest: /etc/network/interfaces.d/interfaces.eth0
    mode: 0644
    owner: root
    group: root
  notify: "restart Debian networking"
  when: ansible_distribution == 'Debian'

- name: Upload resolv.conf configuration
  template:
    src: resolv.conf.j2
    dest: /etc/resolv.conf
    mode: 0644
    owner: root
    group: root
