---
# On RHEL/CentOS7, rpm removal does not stop the service. After removing the
# rpm OTOH we cannot stop the service because there are no unitfiles left.
# So we first test if rpm package is present.
- name: Check if NetworkManager is installed
  command:
    rpm -q NetworkManager
  ignore_errors: True
  register: _rpm_nm_out
  changed_when: False

- name: Stop the Network Manager
  service:
    name: NetworkManager
    state: stopped
    enabled: false
  when: _rpm_nm_out is defined and _rpm_nm_out.rc == 0

- name: Remove Network Manager
  yum:
    name: NetworkManager
    state: absent
  when: _rpm_nm_out is defined and _rpm_nm_out.rc == 0

- name: Make ip configuration static instead of DHCP (RHEL/CentOS)
  template:
    src: ifcfg-eth0.centos.j2
    dest: /etc/sysconfig/network-scripts/ifcfg-eth0
    mode: 0644
    owner: root
    group: root
  notify: "restart RHEL/CentOS networking"

- name: Configure auxilary interface for pxeservers (RHEL/CentOS)
  template:
    src: ifcfg-eth1.centos.j2
    dest: /etc/sysconfig/network-scripts/ifcfg-eth1
    mode: 0644
    owner: root
    group: root
  notify: "restart RHEL/CentOS networking"
  when: inventory_hostname in groups['pxeservers']

- name: Upload resolv.conf configuration
  template:
    src: resolv.conf.j2
    dest: /etc/resolv.conf
    mode: 0644
    owner: root
    group: root

- name: Upload /etc/hosts configuration
  template:
    src: hosts.j2
    dest: /etc/hosts
    mode: 0644
    owner: root
    group: root
