---
- name: Create networking configuration snippets dir (Debian)
  file:
    path: /etc/network/interfaces.d/
    state: directory
    mode: 0750
    owner: root
    group: root
  notify: "restart Debian networking"

- name: Upload lo network configuration snippet (Debian)
  copy:
    src: interfaces.lo.debian
    dest: /etc/network/interfaces.d/interfaces.lo
    mode: 0644
    owner: root
    group: root
  notify: "restart Debian networking"

- name: Upload eth0 network configuration snippet (Debian)
  template:
    src: interfaces.eth0.debian.j2
    dest: /etc/network/interfaces.d/interfaces.eth0
    mode: 0644
    owner: root
    group: root
  notify: "restart Debian networking"

- name: Upload resolv.conf configuration
  template:
    src: resolv.conf.j2
    dest: /etc/resolv.conf
    mode: 0644
    owner: root
    group: root

- name: Upload /etc/hosts configuration
  template:
    src: hosts.j2
    dest: /etc/hosts
    mode: 0644
    owner: root
    group: root
