---
- name: Install base packages for RHEL/CentOS (all versions)
  yum:
    name: "{{ item }}"
    state: present
  with_flattened:
    - base_common_packages
    - base_rhel_common_packages
  when: ansible_os_family == 'RedHat'

- name: Install RHEL/CentOS 6 specific packages
  yum:
    name: "{{ item }}"
    state: present
  with_items: base_rhel6_packages
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version == '6'

- name: Install RHEL/CentOS 7 specific packages
  yum:
    name: "{{ item }}"
    state: present
  with_items: base_rhel7_packages
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'

- name: remove redundant packages (RHEL/CentOS)
  yum:
    name: "{{ item }}"
    state: absent
  with_flattened:
    - base_rhel_redundant_packages
    - base_common_redundant_packages
  when: ansible_os_family == 'RedHat'

- name: Install base packages for Debian
  apt:
    name: "{{ item }}"
    state: present
  with_flattened:
    - base_common_packages
    - base_debian_common_packages
  when: ansible_os_family == 'Debian'

- name: remove redundant packages (Debian)
  apt:
    name: "{{ item }}"
    state: absent
  with_flattened:
    - base_debian_redundant_packages
    - base_common_redundant_packages
  when: ansible_os_family == 'Debian'
