---
- name: Install Python packages for Debian
  apt:
    name: "{{ item.package }}"
    state: present
    default_release: "{{ item.release }}"
  with_items:
    - {"package": "python-pip", "release":"stable"}
    - {"package": "python3", "release":"stable"}
    - {"package": "python3-pip", "release":"stable"}
    - {"package": "python-ipdb", "release":"stable"}
    - {"package": "ipython", "release":"wheezy-backports"}
    - {"package": "ipython3", "release":"wheezy-backports"}
  when: ansible_os_family == 'Debian'

# No ipdb for python3.2, niether backport, niether pip
#- name: Install missing ipdb packages for Debian - python3
#  pip:
#    executable: "{{ item[1] }}"
#    name: "{{ item[0] }}"
#    state: present
#  with_nested:
#    - [ 'ipdb' ]
#    - [ 'pip-3.2' ]
#  when: ansible_os_family == 'Debian'

- name: Install Python packages for RHEL/CentOS
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - python-pip
    - python-ipython
    - python34u
    - python34u-pip
    - python27
    - python27-pip
  when: "ansible_os_family == 'RedHat' and \
        (ansible_distribution_major_version == '6' or \
        ansible_distribution_major_version == '7' and item not in \
        ['python-ipython', 'python27', 'python27-pip'])"

- name: Install missing ipdb/ipython packages for RHEL/CentOS
  pip:
    executable: "{{ item[1] }}"
    name: "{{ item[0] }}"
    state: present
  with_nested:
    - [ 'ipython', 'ipdb' ]
    - [ 'pip3.4', 'pip2.7' ]
  when: ansible_os_family == 'RedHat'
