---
- name: Install Python packages for Debian-like systems
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - python-pip
    - python-ipdb
    - python-virtualenv
    - python3
    - python3-pip
    - python3-ipdb
    - ipython
    - ipython3
  when: >
    ansible_os_family == 'Debian' and
    (ansible_distribution_release != 'wheezy' or
    item.package not in ["ipython", "ipython3", "python3-ipdb", "python3-virtualenv"])

- name: Install missing Python packages for Debian 7 systems
  apt:
    name: "{{ item }}"
    state: present
    default_release: wheezy-backports
  with_items:
    - ipython
    - ipython3
  when: >
    ansible_os_family == 'Debian' and
    ansible_distribution_release == 'wheezy'

# No ipdb for python3.2, niether in backports, niether in pip
- name: Install missing pip packages for Debian 7
  pip:
    executable: "{{ item[1] }}"
    name: "{{ item[0] }}"
    state: present
  with_nested:
    - [ 'ipdb', 'virtualenv' ]
    - [ 'pip-3.2' ]
  when: >
    ansible_os_family == 'Debian' and
    ansible_distribution_release == 'wheezy'

- name: Install Python packages for RHEL/CentOS
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - python-pip
    - python-ipython
    - python-virtualenv
    - python34u
    - python34u-pip
    - python27
    - python27-pip
    - python27-virtualenv
  when: "ansible_os_family == 'RedHat' and \
        (ansible_distribution_major_version == '6' or \
        ansible_distribution_major_version == '7' and item not in \
        ['python-ipython', 'python27', 'python27-pip', 'python27-virtualenv'])"

- name: Install missing ipdb/ipython packages for RHEL/CentOS
  pip:
    executable: "{{ item[1] }}"
    name: "{{ item[0] }}"
    state: present
  with_nested:
    - [ 'ipython', 'ipdb' ]
    - [ 'pip3.4', 'pip2.7', 'pip' ]
  when: "ansible_os_family == 'RedHat' and \
        (ansible_distribution_major_version == '6' and item[1] != 'pip' or \
         ansible_distribution_major_version == '7' and item[1] != 'pip2.7')"
