---
- name: remove cobbler provided repositories (RHEL)
  file:
    name: cobbler-config.repo
    state: absent

- name: add local RPM repos (RHEL)
  template:
    src: local.repo.j2
    dest: /etc/yum.repos.d/local.repo
    mode: 0644
    owner: root
    group: root
  tags: secret

- name: install EPEL repository (RHEL/CentOS 6)
  yum:
    name: http://dl.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm
    state: present
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version == '6'

- name: install EPEL repository (RHEL/CentOS 7)
  yum:
    name: http://dl.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-5.noarch.rpm
    state: present
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'

- name: install IUS repository (RHEL/CentOS 6)
  yum:
    name: http://dl.iuscommunity.org/pub/ius/stable/RedHat/6/x86_64/ius-release-1.0-13.ius.el6.noarch.rpm
    state: present
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version == '6'

- name: install IUS repository (RHEL/CentOS 7)
  yum:
    name: http://dl.iuscommunity.org/pub/ius/stable/RedHat/7/x86_64/ius-release-1.0-13.ius.el7.noarch.rpm
    state: present
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'

- name: purge default repos configuration (Debian)
  file:
    name: /etc/apt/sources.list
    state: absent
  when: ansible_os_family == 'Debian'
  notify: Debian update repos

- name: Set a shortcut for Debian repo name
  set_fact:
    debian_codename="{{'-'.join([ansible_distribution, ansible_distribution_major_version, ansible_architecture])}}"

# netselect-apt: http://ftp.agh.edu.pl/debian/
- name: add debian stable/testing/backport repositories
  apt_repository:
    repo: "{{ item }}"
    state: present
    update_cache: no # will be updated in one row
  with_items:
    - "deb {{ apt_repos[debian_codename] }} {{ ansible_distribution_release }} main contrib non-free"
    - "deb {{ apt_repos[debian_codename] }} {{ ansible_distribution_release }}-updates main contrib non-free"
    - "deb {{ apt_repos[debian_codename] }} {{ ansible_distribution_release }}-backports main contrib non-free"
    - "deb {{ apt_repos[debian_codename] }} jessie main contrib non-free"
    - "deb-src {{ apt_repos[debian_codename] }} {{ ansible_distribution_release }} main contrib non-free"
    - "deb-src {{ apt_repos[debian_codename] }} {{ ansible_distribution_release }}-updates main contrib non-free"
    - "deb-src {{ apt_repos[debian_codename] }} {{ ansible_distribution_release }}-backports main contrib non-free"
    - "deb-src {{ apt_repos[debian_codename] }} jessie main contrib non-free"
    - "deb http://security.debian.org/ {{ ansible_distribution_release }}/updates main contrib non-free"
    - "deb http://security.debian.org/ jessie/updates main contrib non-free"
  when: ansible_os_family == 'Debian'
  notify: Debian update repos

- name: select default Debian release to use
  copy:
    content: 'APT::Default-Release "{{ ansible_distribution_release }}";'
    dest: /etc/apt/apt.conf.d/99defaultrelease
    mode: 0644
    owner: root
    group: root
  when: ansible_os_family == 'Debian'

- name: bump backports priority to 750 (Debian)
  template:
    src: backports.pref.debian.j2
    dest: /etc/apt/preferences.d/backports.pref
    mode: 0644
    owner: root
    group: root
  when: ansible_os_family == 'Debian'
