---
- name: purge default repos configuration (Debian)
  file:
    name: /etc/apt/sources.list
    state: absent
  notify: Debian update repos

- name: Set a shortcut for Debian repo name
  set_fact:
    debian_codename="{{'-'.join([ansible_distribution, ansible_distribution_major_version, ansible_architecture])}}"

- name: Set up debian repos lists
  set_fact:
    debian_repos:
      - "deb {{ apt_repos[debian_codename] }} {{ ansible_distribution_release }} main contrib non-free"
      - "deb {{ apt_repos[debian_codename] }} {{ ansible_distribution_release }}-updates main contrib non-free"
      - "deb {{ apt_repos[debian_codename] }} {{ ansible_distribution_release }}-backports main contrib non-free"
      - "deb {{ apt_repos[debian_codename] }} jessie main contrib non-free"
      - "deb-src {{ apt_repos[debian_codename] }} {{ ansible_distribution_release }} main contrib non-free"
      - "deb-src {{ apt_repos[debian_codename] }} {{ ansible_distribution_release }}-updates main contrib non-free"
      - "deb-src {{ apt_repos[debian_codename] }} {{ ansible_distribution_release }}-backports main contrib non-free"
      - "deb-src {{ apt_repos[debian_codename] }} jessie main contrib non-free"
      - "deb http://security.debian.org/ {{ ansible_distribution_release }}/updates main contrib non-free"
      - "deb http://security.debian.org/ jessie/updates main contrib non-free"

# netselect-apt: http://ftp.agh.edu.pl/debian/
- name: add debian stable/testing/backport repositories
  apt_repository:
    repo: "{{ item }}"
    state: present
    update_cache: no # will be updated in one row
  notify: Debian update repos
  with_items: debian_repos

- name: select default Debian release to use
  copy:
    content: 'APT::Default-Release "{{ ansible_distribution_release }}";'
    dest: /etc/apt/apt.conf.d/99defaultrelease
    mode: 0644
    owner: root
    group: root

- name: bump backports priority to 750 (Debian)
  template:
    src: backports.pref.debian.j2
    dest: /etc/apt/preferences.d/backports.pref
    mode: 0644
    owner: root
    group: root

# Update repository data _NOW_
- meta: flush_handlers
