---
- name: import Draios repository key (RHEL/CentOS)
  rpm_key:
    key: https://s3.amazonaws.com/download.draios.com/DRAIOS-GPG-KEY.public
    state: present
  when: ansible_os_family == 'RedHat'

- name: import Draios repository key (Debian)
  apt_key:
    url: https://s3.amazonaws.com/download.draios.com/DRAIOS-GPG-KEY.public
    state: present
  when: ansible_os_family == 'Debian'

- name: install Draios repository (RHEL/CentOS)
  copy:
    src: draios.repo.centos
    dest: /etc/yum.repos.d/draios.repo
    mode: 0644
    owner: root
    group: root
  when: ansible_os_family == 'RedHat'

- name: install Draios repository (Debian)
  copy:
    src: draios.list.debian
    dest: /etc/apt/sources.list.d/draios.list
    mode: 0644
    owner: root
    group: root
  when: ansible_os_family == 'Debian'

- name: Install kernel headers for RHEL/CentOS (all versions)
  yum:
    name: "kernel-devel-{{ ansible_kernel }}"
    state: present
  when: ansible_os_family == 'RedHat'

- name: Install kernel headers for Debian
  apt:
    name: "linux-headers-{{ ansible_kernel }}"
    state: present
  when: ansible_os_family == 'Debian'

- name: Install sysdig (Debian)
  apt:
    name: sysdig
    state: present
  when: ansible_os_family == 'Debian'

- name: Install sysdig (RHEL/CentOS)
  yum:
    name: sysdig
    state: present
  when: ansible_os_family == 'RedHat'
