---
- name: Install vim packages for RHEL/CentOS (all versions)
  yum:
    name: "{{ item }}"
    state: present
  with_flattened:
    - vim-enhanced-7.4.160
  when: ansible_os_family == 'RedHat'

- name: Install vim packages for Debian
  apt:
    name: "{{ item }}"
    state: present
    default_release: wheezy-backports
  with_flattened:
    - vim-nox
  when: ansible_os_family == 'Debian'

- name: Install vim-related python packages for Debian
  pip:
    executable: "{{ item[1] }}"
    name: "{{ item[0] }}"
    state: present
  with_nested:
    - [ 'jedi', 'flake8' ]
    - [ 'pip-3.2', 'pip' ]
  when: "(ansible_os_family == 'Debian' and item[1] != 'pip-3.4') or \
         (ansible_os_family == 'RedHat' and item[1] != 'pip-3.2')"

- name: Upload vimrc file
  copy:
    src: vimrc
    dest: "/{{ item.key if item.key == 'root' else 'home/' + item.key }}/.vimrc"
    mode: 0640
    owner: "{{ item.key }}"
    group: "{{ item.key }}"
  with_dict: users
  when: item['key'] == 'root' or item['value']['ssh_login_permitted'] == True

- name: Create vim directories
  file:
    name: "/{{ item[1] if item[1] == 'root' else 'home/' + item[1] }}/{{ item[0] }}/"
    state: directory
    mode: 0755
    owner: "{{ item[1] }}"
    group: "{{ item[1] }}"
  with_nested:
    - ['.vim', '.vim/colors', '.vim/autoload', '.vim/bundle', '.vim/ftplugin']
    - users.keys()
  when: item[1] == 'root' or users[item[1]]['ssh_login_permitted'] == True

- name: Upload vim plugins/configs
  copy:
    src: "{{ item[0].name }}"
    dest: "/{{ item[1] if item[1] == 'root' else 'home/' + item[1] }}/.vim/{{ item[0].location }}/{{ item[0].name }}"
    mode: 0640
    owner: "{{ item[1] }}"
    group: "{{ item[1] }}"
  with_nested:
    - [{ name: "python_editing.vim", location: "ftplugin/"}, { name: "wombat256mod.vim", location: "colors/"}, { name: "pathogen.vim", location: "autoload/"}]
    - users.keys()
  when: item[1] == 'root' or users[item[1]]['ssh_login_permitted'] == True

- name: checkout plugins from local git mirrors
  git:
    repo: "ssh://git@{{ '.'.join(nework_configuration[hypervisor]['trusted']['net'].split('.')[:3]) }}.2/home/git/{{ item[0] }}.git/"
    key_file: /root/.ssh/git-mirror_rsa
    dest: "/{{ item[1] if item[1] == 'root' else 'home/' + item[1] }}/.vim/bundle/{{ item[0] }}"
    accept_hostkey: yes
  with_nested:
    - [ 'ctrlp.vim', 'jedi-vim', 'nerdtree', 'vim-airline', 'vim-autoformat', 'vim-flake8' ]
    - users.keys()
  when: proxing_enabled is defined and proxing_enabled == True and (item[1] == 'root' or users[item[1]]['ssh_login_permitted'] == True)

- name: checkout plugins from upstream repos
  git:
    repo: "{{ git_mirror_repos[item[0]]['url'] }}"
    dest: "/{{ item[1] if item[1] == 'root' else 'home/' + item[1] }}/.vim/bundle/{{ item[0] }}"
    accept_hostkey: yes
  with_nested:
    - [ 'ctrlp.vim', 'jedi-vim', 'nerdtree', 'vim-airline', 'vim-autoformat', 'vim-flake8' ]
    - users.keys()
  when: (proxing_enabled is not defined or proxing_enabled == False) and (item[1] == 'root' or users[item[1]]['ssh_login_permitted'] == True)

- name: Set vim as default editor for Debian
  alternatives:
    name: editor
    path: /usr/bin/vim.nox
  when: ansible_os_family == 'Debian'

- name: Set vim as default editor for RHEL/CentOS
  copy:
    content: "export VISUAL='/usr/bin/vim'\nexport EDITOR='/usr/bin/vim'\n"
    dest: /etc/profile.d/editor.sh
    mode: 0755
    owner: root
    group: root
