---
- hosts: all
  become: True
  become_method: sudo
  roles:
    - users_all
    - base_all
    - sshd_config
    - sysdig
    - vim

- hosts: hypervisors
  become: True
  become_method: sudo
  roles:
    - base_hypervisors
    - users_hypervisors
    - disk_schedulers
    - ssh-agent
    - vagrant
    - packer
    - clamav
    - google-stuff
    - flash
    - skype
    - koan_patching
    - dns
    - syncthing
    - development
    - ansible

- hosts: budrys
  become: True
  become_method: sudo
  roles:
    - multiseat

- hosts: vms
  roles:
    - users_vms
    - base_vms
    - disk_schedulers

- hosts: trusted:isolated
  roles:
    - proxy_settings

- hosts: jumphosts
  become: True
  become_method: sudo
  roles:
    - fw_base
    - fw_jumphost

- hosts: mplay:c7t.tr
  become: True
  become_method: sudo
  roles:
    - vagrant

- hosts: pxeservers
  roles:
    - apache2_base
    - proxy
    - repo
    - cobbler

- hosts: packerized
  become: True
  become_method: sudo
  roles:
    - post_provisioning
