---
- name: Remove proxy settings files
  file:
    name: '{{ item }}'
    state: absent
  with_items:
    - /etc/environment
    - /etc/profile.d/proxy.sh
    - /etc/apt/apt.conf.d/80proxy
    - /etc/sysconfig/proxy

- name: Deconfigure proxy settings for yum
  lineinfile:
    dest: /etc/yum.conf
    regexp: '^proxy'
    line: "proxy={{ proxy_settings_yum_proxy }}"
    state: absent
  when: ansible_os_family == 'RedHat' and proxy_settings_yum_proxy is defined

- name: Deconfigure proxy_username for yum
  lineinfile:
    dest: /etc/yum.conf
    regexp: '^proxy_username'
    line: "proxy_username={{ proxy_settings_yum_proxy_username }}"
    state: absent
  when: ansible_os_family == 'RedHat' and proxy_settings_yum_proxy_username is defined

- name: Configure proxy_password for yum
  lineinfile:
    dest: /etc/yum.conf
    regexp: '^proxy_password'
    line: "proxy_password={{ proxy_settings_yum_proxy_password }}"
    state: absent
  when: ansible_os_family == 'RedHat' and proxy_settings_yum_proxy_password is defined
