---
- name: upload sshd configuration
  template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    mode: 0600
    owner: root
    group: root
  notify: restart sshd

- name: create sftp user and shared folder
  user:
    name: sftp
    home: /home/shared/sftp/
    createhome: yes
    password: "{{ sftp_server_pass }}"
    shell: /usr/sbin/nologin
    state: present
    uid: 1005
  when: sshd_config_sftp_server_enabled == True

- name: Add users to sftp group
  user:
    name: "{{ item }}"
    group: sftp
    append: yes
  with_items: users.keys()
  when: >
    (item in local_users or item == 'root') and
    users[item]['is_sftp_user'] == True and
    sshd_config_sftp_server_enabled == True
